# Stage 1: Compile and Build angular codebase

# Use gili-pio-app-image image as the base image
FROM gili-pio-app-image:latest as build

# Set the working directory
WORKDIR /usr/local/app

# Add the source code to app
COPY ./ /usr/local/app/

# Install all the dependencies
RUN npm install

# Generate the build of the application
RUN npm run build
RUN ng build
						sh 'ng serve'
						sh 'ng test'
						sh 'ng e2e'  
						
# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
 